name              'php-xml'
maintainer        'omaze'
maintainer_email  'lucas@omaze.com'
license           'Apache 2.0'
description       'Installs and maintains php-xml and dependencies'
version           '0.0.0'